In [49]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [50]:
html = open(r"C:\Users\merfc\Downloads\veturilo5.html", encoding="utf-8").read()
html2 = open(r"C:\Users\merfc\Downloads\veturilo6.html", encoding="utf-8").read()

In [51]:
def reader(plik): 
    soup = BeautifulSoup(plik, "html.parser")
    
    rows = soup.find_all("div", role="row")
    trips = []
    for i in rows:
        start_place= i.find("div", {"data-field": "startPlace"})
        if not start_place: continue
        end_place = i.find("div", {"data-field": "endPlace"})
        start_time = i.find("div", {"data-field": "startTime"})
        end_time = i.find("div", {"data-field": "endTime"})
        duration = i.find("div", {"data-field": "duration"})
        #bike_type = i.find("div", {"data-field": "bikeType"})
    
        if start_place and end_place:
            trips.append({
                "start_place" : start_place.text.strip(),
                "end_place" : end_place.text.strip() if end_place else None,
                "duration": duration.text.strip() if duration else None,
                "start_time": start_time.text.strip() if start_time else None,
                "end_time": end_time.text.strip() if end_time else None
                #"bike_type": bike_type.text.strip() if bike_type else None,
            })
    return trips

In [52]:
def reader2(plik):
    soup = BeautifulSoup(plik,"html.parser")

    rows = soup.find_all("div",role="row")
    trips = []
    for i in rows:
        bike_type=i.find("div",{"data-field": "bikeType"})
        start_time = i.find("div", {"data-field": "startTime"})
        if bike_type:
            trips.append({
                "bike_type" : bike_type.text.strip(),
                "start_time": start_time.text.strip() if start_time else None
                
            })
    return trips

In [53]:
trips = reader(html)

In [54]:
df1 = pd.DataFrame(trips)

In [55]:
trips2 = reader2(html2)

In [56]:
df2 = pd.DataFrame(trips2)

In [57]:
df = pd.merge(df1, df2, on='start_time')

In [58]:
df = df.drop(0)

In [59]:
df.drop_duplicates(inplace=True)
df = df.reset_index(drop=True)
df

,start_place,end_place,duration,start_time,end_time,bike_type
0,Plac Trzech Krzyży,Krakowskie Przedmieście - Traugutta,6 min,"27.03.2026, 14:50","27.03.2026, 14:56",Elektryczny
1,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,"26.03.2026, 10:53","26.03.2026, 11:02",Standard 4G
2,Rondo Jazdy Polskiej,Stefana Banacha - UW,9 min,"26.03.2026, 09:11","26.03.2026, 09:20",Standard 4G
3,Mokotowska - Piękna,Metro Nowy Świat - Uniwersytet,6 min,"25.03.2026, 14:44","25.03.2026, 14:50",Elektryczny
4,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,"19.03.2026, 10:52","19.03.2026, 11:01",Standard 4G
...,...,...,...,...,...,...
64,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,"10.03.2025, 13:32","10.03.2025, 13:38",Standard 4G
65,Plac Krasińskich,Plac Krasińskich,1 min,"10.03.2025, 13:31","10.03.2025, 13:32",Standard 4G
66,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,7 min,"10.03.2025, 13:31","10.03.2025, 13:38",Standard 4G
67,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,"7.03.2025, 12:42","7.03.2025, 12:46",Standard 4G
68,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,"6.03.2025, 13:04","6.03.2025, 13:08",Standard 4G

In [60]:
moment_startu = pd.to_datetime(df["start_time"])
moment_konca = pd.to_datetime(df["end_time"])
df["start_date"] = moment_startu.dt.date
df["start_time"] = moment_startu.dt.time
df["end_time"] = moment_konca.dt.time
df["end_date"] = moment_konca.dt.date

C:\Users\merfc\AppData\Local\Temp\ipykernel_11024\3048909370.py:1: UserWarning: Parsing dates in %d.%m.%Y, %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  moment_startu = pd.to_datetime(df["start_time"])
C:\Users\merfc\AppData\Local\Temp\ipykernel_11024\3048909370.py:2: UserWarning: Parsing dates in %d.%m.%Y, %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  moment_konca = pd.to_datetime(df["end_time"])

In [61]:
df

,start_place,end_place,duration,start_time,end_time,bike_type,start_date,end_date
0,Plac Trzech Krzyży,Krakowskie Przedmieście - Traugutta,6 min,14:50:00,14:56:00,Elektryczny,2026-03-27,2026-03-27
1,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,10:53:00,11:02:00,Standard 4G,2026-03-26,2026-03-26
2,Rondo Jazdy Polskiej,Stefana Banacha - UW,9 min,09:11:00,09:20:00,Standard 4G,2026-03-26,2026-03-26
3,Mokotowska - Piękna,Metro Nowy Świat - Uniwersytet,6 min,14:44:00,14:50:00,Elektryczny,2026-03-25,2026-03-25
4,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,10:52:00,11:01:00,Standard 4G,2026-03-19,2026-03-19
...,...,...,...,...,...,...,...,...
64,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,13:32:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
65,Plac Krasińskich,Plac Krasińskich,1 min,13:31:00,13:32:00,Standard 4G,2025-03-10,2025-03-10
66,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,7 min,13:31:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
67,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:42:00,12:46:00,Standard 4G,2025-03-07,2025-03-07
68,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,13:04:00,13:08:00,Standard 4G,2025-03-06,2025-03-06