In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
html = open(r"C:\Users\merfc\Downloads\veturilo5.html", encoding="utf-8").read()
html2 = open(r"C:\Users\merfc\Downloads\veturilo6.html", encoding="utf-8").read()

In [3]:
def reader(plik): 
    soup = BeautifulSoup(plik, "html.parser")
    
    rows = soup.find_all("div", role="row")
    trips = []
    for i in rows:
        start_place= i.find("div", {"data-field": "startPlace"})
        if not start_place: continue
        end_place = i.find("div", {"data-field": "endPlace"})
        start_time = i.find("div", {"data-field": "startTime"})
        end_time = i.find("div", {"data-field": "endTime"})
        duration = i.find("div", {"data-field": "duration"})
        #bike_type = i.find("div", {"data-field": "bikeType"})
    
        if start_place and end_place:
            trips.append({
                "start_place" : start_place.text.strip(),
                "end_place" : end_place.text.strip() if end_place else None,
                "duration": duration.text.strip() if duration else None,
                "start_time": start_time.text.strip() if start_time else None,
                "end_time": end_time.text.strip() if end_time else None
                #"bike_type": bike_type.text.strip() if bike_type else None,
            })
    return trips

In [4]:
def reader2(plik):
    soup = BeautifulSoup(plik,"html.parser")

    rows = soup.find_all("div",role="row")
    trips = []
    for i in rows:
        bike_type=i.find("div",{"data-field": "bikeType"})
        start_time = i.find("div", {"data-field": "startTime"})
        if bike_type:
            trips.append({
                "bike_type" : bike_type.text.strip(),
                "start_time": start_time.text.strip() if start_time else None
                
            })
    return trips

In [5]:
trips = reader(html)

In [6]:
df1 = pd.DataFrame(trips)

In [7]:
trips2 = reader2(html2)

In [8]:
df2 = pd.DataFrame(trips2)

In [9]:
df = pd.merge(df1, df2, on='start_time')

In [10]:
df = df.drop(0)

In [11]:
df.drop_duplicates(inplace=True)
df = df.reset_index(drop=True)

In [12]:
moment_startu = pd.to_datetime(df["start_time"])
moment_konca = pd.to_datetime(df["end_time"])
df["start_date"] = moment_startu.dt.date
df["start_time"] = moment_startu.dt.time
df["end_time"] = moment_konca.dt.time
df["end_date"] = moment_konca.dt.date

C:\Users\merfc\AppData\Local\Temp\ipykernel_13736\3048909370.py:1: UserWarning: Parsing dates in %d.%m.%Y, %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  moment_startu = pd.to_datetime(df["start_time"])
C:\Users\merfc\AppData\Local\Temp\ipykernel_13736\3048909370.py:2: UserWarning: Parsing dates in %d.%m.%Y, %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  moment_konca = pd.to_datetime(df["end_time"])

In [13]:
df.sort_values(by="start_date", inplace=True)
df.reset_index(drop=True, inplace=True)
df

,start_place,end_place,duration,start_time,end_time,bike_type,start_date,end_date
0,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,13:04:00,13:08:00,Standard 4G,2025-03-06,2025-03-06
1,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:42:00,12:46:00,Standard 4G,2025-03-07,2025-03-07
2,Plac Krasińskich,Plac Krasińskich,1 min,13:31:00,13:32:00,Standard 4G,2025-03-10,2025-03-10
3,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,13:32:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
4,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,7 min,13:31:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
...,...,...,...,...,...,...,...,...
64,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,10:52:00,11:01:00,Standard 4G,2026-03-19,2026-03-19
65,Mokotowska - Piękna,Metro Nowy Świat - Uniwersytet,6 min,14:44:00,14:50:00,Elektryczny,2026-03-25,2026-03-25
66,Rondo Jazdy Polskiej,Stefana Banacha - UW,9 min,09:11:00,09:20:00,Standard 4G,2026-03-26,2026-03-26
67,Stefana Banacha - UW,Rondo Jazdy Polskiej,9 min,10:53:00,11:02:00,Standard 4G,2026-03-26,2026-03-26
68,Plac Trzech Krzyży,Krakowskie Przedmieście - Traugutta,6 min,14:50:00,14:56:00,Elektryczny,2026-03-27,2026-03-27

In [14]:
df["start_date"] = pd.to_datetime(df["start_date"])
df["end_date"] = pd.to_datetime(df["end_date"])

df2025 = df[df["start_date"].dt.year == 2025]
df2025

,start_place,end_place,duration,start_time,end_time,bike_type,start_date,end_date
0,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,13:04:00,13:08:00,Standard 4G,2025-03-06,2025-03-06
1,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:42:00,12:46:00,Standard 4G,2025-03-07,2025-03-07
2,Plac Krasińskich,Plac Krasińskich,1 min,13:31:00,13:32:00,Standard 4G,2025-03-10,2025-03-10
3,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,13:32:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
4,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,7 min,13:31:00,13:38:00,Standard 4G,2025-03-10,2025-03-10
5,Krakowskie Przedmieście - Traugutta,Plac Krasińskich,4 min,09:37:00,09:41:00,Standard 4G,2025-03-27,2025-03-27
6,Metro Młociny,Świderska - Świętosławskiego,14 min,13:29:00,13:43:00,Standard 4G,2025-03-27,2025-03-27
7,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:24:00,12:28:00,Standard 4G,2025-03-28,2025-03-28
8,Świderska - Świętosławskiego,Metro Młociny,15 min,09:43:00,09:57:00,Standard 4G,2025-03-31,2025-03-31
9,Rondo Jazdy Polskiej,Stefana Banacha - UW,8 min,15:58:00,16:06:00,Standard 4G,2025-03-31,2025-03-31
10,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,11:10:00,11:16:00,Standard 4G,2025-04-15,2025-04-15
11,Świderska - Świętosławskiego,Metro Młociny,15 min,16:43:00,16:58:00,Standard 4G,2025-04-20,2025-04-20
12,Świderska - Świętosławskiego,Metro Młociny,15 min,16:44:00,16:59:00,Elektryczny,2025-04-20,2025-04-20
13,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,5 min,13:06:00,13:10:00,Standard 4G,2025-04-28,2025-04-28
14,Krakowskie Przedmieście - Traugutta,Metro Dworzec Gdański,13 min,16:11:00,16:24:00,Standard 4G,2025-04-28,2025-04-28
15,Rondo Jazdy Polskiej,Stefana Banacha - UW,8 min,15:50:00,15:58:00,Standard 4G,2025-05-05,2025-05-05
16,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,5 min,13:01:00,13:07:00,Standard 4G,2025-05-12,2025-05-12
17,Ochota-Ratusz,Metro Rondo Daszyńskiego,4 min,15:30:00,15:34:00,Standard 4G,2025-05-14,2025-05-14
18,Ochota-Ratusz,Metro Rondo Daszyńskiego,4 min,21:34:00,21:38:00,Elektryczny,2025-05-17,2025-05-17
19,Plac Krasińskich,Metro Nowy Świat - Uniwersytet,6 min,12:31:00,12:37:00,Standard 4G,2025-05-23,2025-05-23
20,Metro Młociny,Świderska - Świętosławskiego,12 min,22:20:00,22:33:00,Standard 4G,2025-05-25,2025-05-25
21,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,5 min,13:00:00,13:06:00,Standard 4G,2025-05-26,2025-05-26
22,Lipowa - Dobra,Park Kępa Potocka,21 min,16:10:00,16:31:00,Standard 4G,2025-05-26,2025-05-26
23,Świderska - Świętosławskiego,Metro Młociny,17 min,07:21:00,07:38:00,Standard 4G,2025-05-27,2025-05-27
24,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:59:00,13:03:00,Standard 4G,2025-05-29,2025-05-29
25,Mokotowska - Piękna,Metro Nowy Świat - Uniwersytet,10 min,15:07:00,15:17:00,Standard 4G,2025-05-29,2025-05-29
26,Plac Krasińskich,Plac Krasińskich,0 min,09:31:00,09:31:00,Standard 4G,2025-05-30,2025-05-30
27,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,4 min,12:19:00,12:24:00,Standard 4G,2025-05-30,2025-05-30
28,Metro Rondo Daszyńskiego,Okopowa - Anielewicza,9 min,15:02:00,15:11:00,Standard 4G,2025-06-05,2025-06-05
29,Okopowa - Anielewicza,Świderska - Świętosławskiego,43 min,15:11:00,15:55:00,Standard 4G,2025-06-05,2025-06-05
30,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,5 min,12:24:00,12:28:00,Standard 4G,2025-06-06,2025-06-06
31,al. Reymonta - Conrada,Świderska - Świętosławskiego,36 min,22:52:00,23:29:00,Standard 4G,2025-06-13,2025-06-13
32,al. Reymonta - Conrada,Świderska - Świętosławskiego,36 min,22:53:00,23:29:00,Standard 4G,2025-06-13,2025-06-13
33,Blue City,Chrościckiego – al. 4 Czerwca 1989 r.,17 min,15:03:00,15:19:00,Standard 4G,2025-07-23,2025-07-23
34,Modlińska - Żerańska,Świderska - Świętosławskiego,14 min,16:12:00,16:26:00,Standard 4G,2025-10-02,2025-10-02
35,Metro Młociny,Świderska - Świętosławskiego,12 min,16:43:00,16:56:00,Standard 4G,2025-10-05,2025-10-05
36,Krakowskie Przedmieście - Traugutta,Plac Krasińskich,4 min,13:03:00,13:07:00,Standard 4G,2025-10-07,2025-10-07
37,Krakowskie Przedmieście - Traugutta,Krakowskie Przedmieście - Traugutta,1 min,11:18:00,11:19:00,Standard 4G,2025-10-10,2025-10-10
38,Strefa zwrotu roweru,Plac Krasińskich,4 min,11:23:00,11:27:00,Standard 4G,2025-10-17,2025-10-17
39,Plac Krasińskich,Krakowskie Przedmieście - Traugutta,6 min,15:15:00,15:21:00,Standard 4G,2025-10-21,2025-10-21
40,Plac Krasińskich,Świderska - Świętosławskiego,31 min,14:53:00,15:24:00,Standard 4G,2025-10-22,2025-10-22
41,Krakowskie Przedmieście - Traugutta,Plac Krasińskich,4 min,13:10:00,13:15:00,Standard 4G,2025-10-28,2025-10-28
42,Miodowa,Plac Krasińskich,3 min,07:52:00,07:55:00,Standard 4G,2025-10-29,2025-10-29
43,Metro Młociny,Świderska - Świętosławskiego,13 min,19:13:00,19:26:00,Standard 4G,2025-11-03,2025-11-03
44,Krakowskie Przedmieście - Trębacka,Świderska - Świętosławskiego,39 min,10:01:00,10:41:00,Standard 4G,2025-11-04,2025-11-04
45,Metro Młociny,Świderska - Świętosławskiego,13 min,11:36:00,11:49:00,Standard 4G,2025-11-06,2025-11-06
46,Andersa - Długa,Krakowskie Przedmieście - Traugutta,5 min,13:14:00,13:19:00,Standard 4G,2025-11-07,2025-11-07
47,Metro Młociny,Świderska - Świętosławskiego,14 min,20:12:00,20:26:00,Standard 4G,2025-11-18,2025-11-18
48,Krakowskie Przedmieście - Traugutta,Plac Krasińskich,4 min,11:21:00,11:25:00,Standard 4G,2025-11-21,2025-11-21

In [15]:
print(len(df[df["start_date"].dt.year == 2026]))
#df[df["start_date"].dt.year == 2026]

20

Ogarnijmy dystans

In [16]:
from distance import dystans

['']

In [ ]:
dystans(df2025["start_place"][33],df2025["end_place"][33]) # nie ma sensu trzeba znalezc baze danych stacji veturilo i porownac z tymi danymi, bo google maps nie rozpoznaje tych nazw stacji

'Brak'